# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recolens.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'recolens.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erecolens.proto\x12\x08recolens\"i\n\x04Item\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x11\n\tauthor_id\x18\x05 \x01(\t\x12\x12\n\ncreated_ts\x18\x06 \x01(\x03\">\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tinterests\x18\x02 \x03(\t\x12\x12\n\ncreated_ts\x18\x03 \x01(\x03\"Z\n\x0bInteraction\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12\r\n\x05\x65vent\x18\x03 \x01(\t\x12\n\n\x02ts\x18\x04 \x01(\x03\x12\x0e\n\x06weight\x18\x05 \x01(\x02\",\n\nScoredItem\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\"F\n\x0eRecommendation\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12#\n\x05items\x18\x02 \x03(\x0b\x32\x14.recolens.ScoredItemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recolens_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM']._serialized_start=28
  _globals['_ITEM']._serialized_end=133
  _globals['_USER']._serialized_start=135
  _globals['_USER']._serialized_end=197
  _globals['_INTERACTION']._serialized_start=199
  _globals['_INTERACTION']._serialized_end=289
  _globals['_SCOREDITEM']._serialized_start=291
  _globals['_SCOREDITEM']._serialized_end=335
  _globals['_RECOMMENDATION']._serialized_start=337
  _globals['_RECOMMENDATION']._serialized_end=407
# @@protoc_insertion_point(module_scope)
