"""Generate a self-contained KPI / A-B report (docs/demo-viewer/index.html).

Runs the default eval + A-B and emits a single static HTML file (inline CSS +
SVG, no external deps, no network) — the demo surface for the eval harness.
Deterministic for a fixed seed.
"""

from __future__ import annotations

import html
from pathlib import Path

from recolens.core.ab import ab_compare
from recolens.core.evaluate import build_qrels, run_eval, time_split
from recolens.core.schema import parse_interactions, parse_items
from recolens.packs.ugc.baselines import ContentRanker, PopularityRanker
from recolens.packs.ugc.reco_collab import CollaborativeRanker
from recolens.packs.ugc.reco_hybrid import HybridRanker
from recolens.packs.ugc.synth import generate

OUT = Path(__file__).resolve().parents[1] / "docs" / "demo-viewer" / "index.html"


def _bar(value: float, vmax: float, color: str, width: int = 220) -> str:
    w = int((value / vmax) * width) if vmax > 0 else 0
    return (
        f'<svg width="{width}" height="14">'
        f'<rect width="{width}" height="14" fill="#eee"/>'
        f'<rect width="{w}" height="14" fill="{color}"/></svg>'
    )


def build(seed: int = 42) -> str:
    data = generate(n_items=300, n_users=80, seed=seed)
    items = parse_items(data["items"]).valid
    inter = parse_interactions(data["interactions"]).valid
    train, test = time_split(inter, 0.3)

    rankers = [
        PopularityRanker(),
        ContentRanker(dim=64),
        CollaborativeRanker(),
        HybridRanker(dim=64),
    ]
    _q, results, _r = run_eval(items, train, test, rankers, ks=(5, 10))

    qrels = build_qrels(test)
    users = sorted(qrels)
    ra, rb = ContentRanker(dim=64), CollaborativeRanker()  # A = content, B = collaborative
    ra.fit(items, train)
    rb.fit(items, train)
    runs_a = {u: ra.rank(u, 10) for u in users}
    runs_b = {u: rb.rank(u, 10) for u in users}
    ab = ab_compare(qrels, runs_a, runs_b, k=10, seed=seed)

    metric_names = sorted({m for r in results.values() for m in r})
    names = list(results.keys())

    rows = []
    for m in metric_names:
        vmax = max(results[n][m] for n in names) or 1.0
        cells = "".join(
            f"<td>{results[n][m]:.4f} {_bar(results[n][m], vmax, '#3b82f6' if n == 'collab' else '#9ca3af')}</td>"
            for n in names
        )
        rows.append(f"<tr><th>{html.escape(m)}</th>{cells}</tr>")
    head = "".join(f"<th>{html.escape(n)}</th>" for n in names)

    decision_color = {"B wins": "#16a34a", "A wins": "#dc2626"}.get(str(ab["decision"]), "#ca8a04")

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>recolens — KPI / A-B report</title>
<style>
 body{{font-family:system-ui,sans-serif;max-width:860px;margin:2rem auto;color:#111;padding:0 1rem}}
 h1{{margin-bottom:.2rem}} .sub{{color:#666;margin-top:0}}
 table{{border-collapse:collapse;width:100%;margin:1rem 0}}
 th,td{{border:1px solid #ddd;padding:.4rem .6rem;text-align:left;font-variant-numeric:tabular-nums}}
 thead th{{background:#f8fafc}}
 .card{{border:1px solid #e5e7eb;border-radius:10px;padding:1rem 1.2rem;margin:1rem 0;background:#fafafa}}
 .kpi{{font-size:1.4rem;font-weight:700}} .badge{{display:inline-block;background:#111;color:#fff;border-radius:6px;padding:.1rem .5rem;font-size:.8rem;margin-right:.3rem}}
 code{{background:#f1f5f9;padding:.05rem .3rem;border-radius:4px}}
</style></head><body>
<h1>recolens — offline evaluation</h1>
<p class="sub">content recommendation &amp; search · KPI / A-B / cost-latency · local &amp; free</p>
<p><span class="badge">seed {seed}</span><span class="badge">300 items</span><span class="badge">80 users</span><span class="badge">temporal split 0.3</span></p>

<h2>Ranking quality — four methods</h2>
<p>Metrics follow BEIR / ir_measures definitions and are unit-cross-checked against <code>ir_measures</code>. Stable ordering across seeds: <b>collaborative &gt; hybrid &gt; content &gt; popularity</b>. The hybrid does not beat collaborative here — an honest negative result (a sharp signal is diluted by fusion).</p>
<table><thead><tr><th>metric</th>{head}</tr></thead><tbody>{"".join(rows)}</tbody></table>

<h2>A-B simulation — KPI = hit-rate@{ab["k"]}</h2>
<div class="card">
 <div>A = <b>content</b> &nbsp; B = <b>collaborative</b> &nbsp; (n={ab["n"]} users)</div>
 <p class="kpi">KPI_A {ab["kpi_a"]:.4f} &rarr; KPI_B {ab["kpi_b"]:.4f}
   &nbsp; lift {ab["abs_lift"]:+.4f} ({ab["rel_lift"]:+.1%})</p>
 <div>95% bootstrap CI (B−A): [{ab["ci95_low"]:+.4f}, {ab["ci95_high"]:+.4f}]</div>
 <div>decision: <b style="color:{decision_color}">{html.escape(str(ab["decision"]))}</b></div>
 <p class="sub">The CI qualifies the win — a positive point lift with a CI crossing zero is reported as inconclusive, not a win.</p>
</div>
<p class="sub">Generated by <code>scripts/gen_report.py</code> — deterministic, offline, no external services.</p>
</body></html>
"""


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
